name: pytorch_base
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.0.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - anyio=3.3.2
  - argon2-cffi=20.1.0
  - async-timeout=4.0.1
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.4
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cachetools=4.2.4
  - captum=0.4.0
  - catalogue=2.0.6
  - certifi=2021.10.8
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - click=8.0.3
  - colorama=0.4.4
  - cryptography=3.4.7
  - cudatoolkit=10.2.89
  - cycler=0.10.0
  - cymem=2.0.6
  - cython-blis=0.7.4
  - dataclasses=0.8
  - debugpy=1.4.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - easygui=0.98.1
  - entrypoints=0.3
  - ffmpeg=4.3
  - fonttools=4.25.0
  - freetype=2.10.4
  - frozenlist=1.2.0
  - fsspec=2021.11.1
  - future=0.18.2
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=2.3.3
  - google-auth-oauthlib=0.4.6
  - grpcio=1.42.0
  - idna=3.1
  - importlib-metadata=4.8.1
  - intel-openmp=2021.3.0
  - ipykernel=6.4.1
  - ipympl=0.8.2
  - ipython=7.28.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.0
  - jinja2=3.0.1
  - joblib=0.17.0
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=4.0.1
  - jupyter_client=7.0.5
  - jupyter_core=4.8.1
  - jupyter_server=1.11.0
  - jupyterlab=3.1.14
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.8.2
  - jupyterlab_widgets=1.0.2
  - kiwisolver=1.3.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libprotobuf=3.15.8
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp-base=1.2.0
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - markdown=3.3.6
  - markupsafe=2.0.1
  - matplotlib-base=3.4.2
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - multidict=5.2.0
  - munkres=1.1.4
  - murmurhash=1.0.6
  - nbclassic=0.3.2
  - nbclient=0.5.4
  - nbconvert=6.2.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - nettle=3.7.3
  - ninja=1.10.2
  - notebook=6.4.4
  - numexpr=2.7.3
  - numpy=1.20.3
  - numpy-base=1.20.3
  - oauthlib=3.1.1
  - olefile=0.46
  - openh264=2.1.0
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=1.3.4
  - pandoc=2.14.2
  - pandocfilters=1.5.0
  - parso=0.8.2
  - pathy=0.6.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.2.4
  - preshed=3.0.6
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.20
  - protobuf=3.15.8
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pydantic=1.8.2
  - pydeprecate=0.3.1
  - pygments=2.10.0
  - pyjwt=2.3.0
  - pyopenssl=21.0.0
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.10.0
  - pytorch-lightning=1.5.4
  - pytorch-mutex=1.0
  - pytz=2021.1
  - pyu2f=0.1.5
  - pyzmq=19.0.2
  - readline=8.1
  - requests=2.26.0
  - requests-oauthlib=1.3.0
  - requests-unixsocket=0.2.0
  - rsa=4.8
  - scikit-learn=1.0.1
  - scipy=1.7.1
  - send2trash=1.8.0
  - setuptools=58.0.4
  - shellingham=1.4.0
  - six=1.16.0
  - smart_open=5.2.1
  - sniffio=1.2.0
  - spacy=3.1.3
  - spacy-legacy=3.0.8
  - sqlite=3.36.0
  - srsly=2.4.2
  - tensorboard=2.7.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.0
  - terminado=0.12.1
  - testpath=0.5.0
  - thinc=8.0.11
  - threadpoolctl=2.1.0
  - tk=8.6.11
  - torchaudio=0.10.0
  - torchmetrics=0.6.0
  - torchtext=0.11.0
  - torchvision=0.11.1
  - tornado=6.1
  - tqdm=4.62.2
  - traitlets=5.1.0
  - typer=0.4.0
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - tzdata=2021a
  - urllib3=1.26.7
  - wasabi=0.8.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.57.0
  - werkzeug=2.0.1
  - wheel=0.37.0
  - widgetsnbextension=3.5.2
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.7.2
  - zeromq=4.3.4
  - zipp=3.5.1
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - de-core-news-sm==3.1.0
    - efficientnet-pytorch==0.7.1
    - en-core-web-sm==3.1.0
    - pyyaml==5.4.1
    - torch-summary==1.4.5
    - torch-tb-profiler==0.3.1
    - torchsummary==1.5.1
